#!/usr/bin/env bash
#loops from 1 to 10, prints bad luck on 4 and good luck on 8 and Best School for the others
var='Best School'
i=1
while [ $i -lt 11 ]
do
	if [ "$i" = 4 ]
	then
		echo "bad luck"
	elif [ "$i" = 8 ]
	then
	    echo "good luck"
	else
		echo "$var"
	fi
	i=$((i + 1))
done
