#!/usr/bin/env bash
#prints numbers from 1 to 20, prints bad luck from China on the 4th, bad luck from Japan on the 9th and bad luck from Italy
i=1
while [ $i -lt 21 ]
do
	case $i in 
	4) 
	    echo $i
		echo "bad luck from China"
		;;
	9) 
	    echo $i
		echo "bad luck from Japan"
		;;
	17) 
	    echo $i
		echo "bad luck from Italy"
		;;
	*) echo "$i";;
	esac
	i=$((i + 1))
done
